name: stupel
description: STUPEL - Student Planner App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  flutter_slidable: ^3.1.0
  iconsax: ^0.0.8
  flutter_quill: ^11.5.0
  image_picker: ^1.0.8
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
